Netlist(Freeze)
Netlist(Clear)
Netlist(Add,unnamed_net3,Z3-2)
Netlist(Add,unnamed_net3,XTAL3-2)
Netlist(Add,unnamed_net3,CONN2-4)
Netlist(Add,unnamed_net2,Z2-2)
Netlist(Add,unnamed_net2,XTAL2-2)
Netlist(Add,unnamed_net2,CONN2-2)
Netlist(Add,unnamed_net1,CONN1-2)
Netlist(Add,unnamed_net1,Z1-2)
Netlist(Add,unnamed_net1,XTAL1-2)
Netlist(Add,GND,CONN2-3)
Netlist(Add,GND,Z3-1)
Netlist(Add,GND,XTAL3-1)
Netlist(Add,GND,CONN2-1)
Netlist(Add,GND,Z2-1)
Netlist(Add,GND,XTAL2-1)
Netlist(Add,GND,CONN1-1)
Netlist(Add,GND,Z1-1)
Netlist(Add,GND,XTAL1-1)
Netlist(Sort)
Netlist(Thaw)
ElementList(Start)
ElementList(Need,"Z3","foot/Diodes_SMA.lht","unknown")
ElementSetAttr("Z3","device","ZENER_DIODE")
ElementSetAttr("Z3","manufacturer","unknown")
ElementSetAttr("Z3","manufacturer_part_number","unknown")
ElementSetAttr("Z3","vendor","unknown")
ElementSetAttr("Z3","vendor_part_number","unknown")
ChangePinName("Z3", 1, "1")
ChangePinName("Z3", 2, "2")
ElementList(Need,"XTAL3","DBlimited_‎P08080-1‎.subc.lht","unknown")
ElementSetAttr("XTAL3","device","CRYSTAL")
ElementSetAttr("XTAL3","manufacturer","unknown")
ElementSetAttr("XTAL3","manufacturer_part_number","unknown")
ElementSetAttr("XTAL3","vendor","unknown")
ElementSetAttr("XTAL3","vendor_part_number","unknown")
ChangePinName("XTAL3", 2, "2")
ChangePinName("XTAL3", 1, "1")
ElementList(Need,"Z2","Diodes_SMA.lht","unknown")
ElementSetAttr("Z2","device","ZENER_DIODE")
ElementSetAttr("Z2","manufacturer","unknown")
ElementSetAttr("Z2","manufacturer_part_number","unknown")
ElementSetAttr("Z2","vendor","unknown")
ElementSetAttr("Z2","vendor_part_number","unknown")
ChangePinName("Z2", 1, "1")
ChangePinName("Z2", 2, "2")
ElementList(Need,"XTAL2","DBlimited_‎P08080-1‎.subc.lht","unknown")
ElementSetAttr("XTAL2","device","CRYSTAL")
ElementSetAttr("XTAL2","manufacturer","unknown")
ElementSetAttr("XTAL2","manufacturer_part_number","unknown")
ElementSetAttr("XTAL2","vendor","unknown")
ElementSetAttr("XTAL2","vendor_part_number","unknown")
ChangePinName("XTAL2", 2, "2")
ChangePinName("XTAL2", 1, "1")
ElementList(Need,"CONN2","unknown","unknown")
ElementSetAttr("CONN2","device","CONNECTOR_4")
ElementSetAttr("CONN2","manufacturer","unknown")
ElementSetAttr("CONN2","manufacturer_part_number","unknown")
ElementSetAttr("CONN2","vendor","unknown")
ElementSetAttr("CONN2","vendor_part_number","unknown")
ChangePinName("CONN2", 1, "1")
ChangePinName("CONN2", 4, "4")
ChangePinName("CONN2", 2, "2")
ChangePinName("CONN2", 3, "3")
ElementList(Need,"CONN1","unknown","unknown")
ElementSetAttr("CONN1","device","CONNECTOR_2")
ElementSetAttr("CONN1","manufacturer","unknown")
ElementSetAttr("CONN1","manufacturer_part_number","unknown")
ElementSetAttr("CONN1","vendor","unknown")
ElementSetAttr("CONN1","vendor_part_number","unknown")
ChangePinName("CONN1", 1, "1")
ChangePinName("CONN1", 2, "2")
ElementList(Need,"Z1","Diodes_SMA.lht","unknown")
ElementSetAttr("Z1","device","ZENER_DIODE")
ElementSetAttr("Z1","manufacturer","unknown")
ElementSetAttr("Z1","manufacturer_part_number","unknown")
ElementSetAttr("Z1","vendor","unknown")
ElementSetAttr("Z1","vendor_part_number","unknown")
ChangePinName("Z1", 1, "1")
ChangePinName("Z1", 2, "2")
ElementList(Need,"XTAL1","DBlimited_‎P08080-1‎.subc.lht","unknown")
ElementSetAttr("XTAL1","device","CRYSTAL")
ElementSetAttr("XTAL1","manufacturer","unknown")
ElementSetAttr("XTAL1","manufacturer_part_number","unknown")
ElementSetAttr("XTAL1","vendor","unknown")
ElementSetAttr("XTAL1","vendor_part_number","unknown")
ChangePinName("XTAL1", 2, "2")
ChangePinName("XTAL1", 1, "1")
ElementList(Done)
