Netlist(Freeze)
Netlist(Clear)
Netlist(Add,unnamed_net6,Z1-2)
Netlist(Add,unnamed_net6,XTAL1-2)
Netlist(Add,unnamed_net6,CONN3-1)
Netlist(Add,unnamed_net5,Z1-1)
Netlist(Add,unnamed_net5,XTAL1-1)
Netlist(Add,unnamed_net5,CONN3-2)
Netlist(Add,unnamed_net4,Z1-2)
Netlist(Add,unnamed_net4,XTAL1-2)
Netlist(Add,unnamed_net4,CONN2-1)
Netlist(Add,unnamed_net3,Z1-1)
Netlist(Add,unnamed_net3,XTAL1-1)
Netlist(Add,unnamed_net3,CONN2-2)
Netlist(Add,unnamed_net2,CONN1-1)
Netlist(Add,unnamed_net2,Z1-2)
Netlist(Add,unnamed_net2,XTAL1-2)
Netlist(Add,unnamed_net1,CONN1-2)
Netlist(Add,unnamed_net1,Z1-1)
Netlist(Add,unnamed_net1,XTAL1-1)
Netlist(Sort)
Netlist(Thaw)
ElementList(Start)
ElementList(Need,"XTAL4","DBlimited_P08080-1.subc.lht","unknown")
ElementSetAttr("XTAL4","device","CRYSTAL")
ElementSetAttr("XTAL4","manufacturer","unknown")
ElementSetAttr("XTAL4","manufacturer_part_number","unknown")
ElementSetAttr("XTAL4","vendor","unknown")
ElementSetAttr("XTAL4","vendor_part_number","unknown")
ChangePinName("XTAL4", 2, "2")
ChangePinName("XTAL4", 1, "1")
ElementList(Need,"Z1","Diodes_SMA.lht","unknown")
ElementSetAttr("Z1","device","ZENER_DIODE")
ElementSetAttr("Z1","manufacturer","unknown")
ElementSetAttr("Z1","manufacturer_part_number","unknown")
ElementSetAttr("Z1","vendor","unknown")
ElementSetAttr("Z1","vendor_part_number","unknown")
ChangePinName("Z1", 1, "1")
ChangePinName("Z1", 2, "2")
ChangePinName("Z1", 1, "1")
ChangePinName("Z1", 2, "2")
ChangePinName("Z1", 1, "1")
ChangePinName("Z1", 2, "2")
ElementList(Need,"CONN3","connector(2, 1, spacing=3.25000000mm, pin_ringdia=2.50000000mm, pin_mask=3.00000000mm, pin_drill=1.50000000mm, silkmark=external)","unknown")
ElementSetAttr("CONN3","device","CONNECTOR_2")
ElementSetAttr("CONN3","manufacturer","unknown")
ElementSetAttr("CONN3","manufacturer_part_number","unknown")
ElementSetAttr("CONN3","vendor","unknown")
ElementSetAttr("CONN3","vendor_part_number","unknown")
ChangePinName("CONN3", 1, "1")
ChangePinName("CONN3", 2, "2")
ElementList(Need,"CONN2","connector(2, 1, spacing=3.25000000mm, pin_ringdia=2.50000000mm, pin_mask=3.00000000mm, pin_drill=1.50000000mm, silkmark=external)","unknown")
ElementSetAttr("CONN2","device","CONNECTOR_2")
ElementSetAttr("CONN2","manufacturer","unknown")
ElementSetAttr("CONN2","manufacturer_part_number","unknown")
ElementSetAttr("CONN2","vendor","unknown")
ElementSetAttr("CONN2","vendor_part_number","unknown")
ChangePinName("CONN2", 1, "1")
ChangePinName("CONN2", 2, "2")
ElementList(Need,"CONN1","connector(2, 1, spacing=3.25000000mm, pin_ringdia=2.50000000mm, pin_mask=3.00000000mm, pin_drill=1.50000000mm, silkmark=external)","unknown")
ElementSetAttr("CONN1","device","CONNECTOR_2")
ElementSetAttr("CONN1","manufacturer","unknown")
ElementSetAttr("CONN1","manufacturer_part_number","unknown")
ElementSetAttr("CONN1","vendor","unknown")
ElementSetAttr("CONN1","vendor_part_number","unknown")
ChangePinName("CONN1", 1, "1")
ChangePinName("CONN1", 2, "2")
ElementList(Need,"XTAL1","DBlimited_P08080-1.subc.lht","unknown")
ElementSetAttr("XTAL1","device","CRYSTAL")
ElementSetAttr("XTAL1","manufacturer","unknown")
ElementSetAttr("XTAL1","manufacturer_part_number","unknown")
ElementSetAttr("XTAL1","vendor","unknown")
ElementSetAttr("XTAL1","vendor_part_number","unknown")
ChangePinName("XTAL1", 2, "2")
ChangePinName("XTAL1", 1, "1")
ChangePinName("XTAL1", 2, "2")
ChangePinName("XTAL1", 1, "1")
ChangePinName("XTAL1", 2, "2")
ChangePinName("XTAL1", 1, "1")
ElementList(Done)
